# This is the main configuration file that sources all modules
# Place this in ~/.config/hypr/hyprland.conf

################################################################################
# SOURCE CONFIGURATION MODULES
################################################################################

source = ~/.config/hypr/colors/catppuccin.conf
source = ~/.config/hypr/modules/monitors.conf
source = ~/.config/hypr/modules/autostart.conf
source = ~/.config/hypr/modules/env.conf
source = ~/.config/hypr/modules/input.conf
source = ~/.config/hypr/modules/general.conf
source = ~/.config/hypr/modules/decorations.conf
source = ~/.config/hypr/modules/animations.conf
source = ~/.config/hypr/modules/layouts.conf
source = ~/.config/hypr/modules/misc.conf
source = ~/.config/hypr/modules/keybindings.conf
source = ~/.config/hypr/modules/windowrules.conf
source = ~/.config/hypr/modules/workspaces.conf

