################################################################################
# AUTOSTART
################################################################################

# Clipboard
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Wallpaper
exec-once = swww-daemon

# Tray
exec-once = nm-applet
exec-once = blueman-applet
exec-once = swaync

# Status bar
exec-once = waybar

# Authentication
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Idle
exec-once = hypridle

# RGB
exec-once = openrgb --startminimized --profile ~/.config/OpenRGB/Catppucin.orp

# Dropbox
exec-once = dropbox

# Volume Pill
exec-once = swayosd-server
exec-once = pkexec swayosd-libinput-backend

# ActivityWatch
exec-once = /opt/activitywatch/aw-server/aw-server
exec-once = /opt/activitywatch/aw-watcher-afk/aw-watcher-afk
exec-once = /opt/activitywatch/aw-watcher-window/aw-watcher-window

# Gnome Keyings
exec-once = gnome-keyring-daemon --start --components=secrets
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# OmniRoute
exec-once = omniroute