################################################################################
# FILE: ~/.config/hypr/modules/decorations.conf
################################################################################

# Window decorations

decoration {
    rounding = 16

    # Opacity
    active_opacity = 1.0
    inactive_opacity = 1.0
    fullscreen_opacity = 1.0

    # Dim
    dim_inactive = false
    dim_strength = 0.05
    dim_special = 0.5

    # Shadows
    shadow {
        enabled = true
        range = 20
        render_power = 3
        color = rgba(000000aa)
        offset = 0 0
        scale = 1.0
    }

    # Blur
    blur {
        enabled = true
        size = 8
        passes = 3
        new_optimizations = true
        xray = true
        ignore_opacity = true
        noise = 0.02
        contrast = 1.0
        brightness = 1.0
        vibrancy = 0.1696
        vibrancy_darkness = 0.0
        special = false
        popups = true
        popups_ignorealpha = 0.2
    }
}