################################################################################
# FILE: ~/.config/hypr/modules/general.conf
################################################################################

# General window and workspace settings

general {
    gaps_in = 2
    gaps_out = 8
    border_size = 1

    # Border colors
    col.active_border = $lavender
    col.inactive_border = $lavender

    # Layouts
    layout = dwindle

    # Allow tearing for games
    allow_tearing = false

    resize_on_border = true
    extend_border_grab_area = 15
    hover_icon_on_border = true

    no_focus_fallback = false
}