################################################################################
# FILE: ~/.config/hypr/modules/misc.conf
################################################################################

misc {
    disable_hyprland_logo         = true
    disable_splash_rendering      = true
    force_default_wallpaper       = 0
    vrr                           = 0
    mouse_move_enables_dpms       = true
    key_press_enables_dpms        = true
    always_follow_on_dnd          = true
    layers_hog_keyboard_focus     = true
    animate_manual_resizes        = false
    animate_mouse_windowdragging  = false
    disable_autoreload            = false
    enable_swallow                = true
    swallow_regex                 = ^(kitty|alacritty|foot)$
    focus_on_activate             = true
    mouse_move_focuses_monitor    = true
    background_color              = 0x111111
    # disable_splash_rendering      = true
}

xwayland {
    force_zero_scaling = true
}

cursor {
    no_hardware_cursors = true
}

render {
    direct_scanout = false  # disabled - causes random blinking on Nvidia
}