################################################################################
# FILE: ~/.config/hypr/modules/monitors.conf
################################################################################

# Monitor configuration
# Use 'hyprctl monitors' to get monitor names
# Format: monitor=name,resolution@refresh,position,scale

# Auto configure monitors
# monitor=,1920x1080@200,auto,1

# Example manual configurations:
monitor=DP-1,1920x1080@165,0x0,1
# monitor=HDMI-A-2,1920x1080@165,0x0,1,bitdepth,8
# monitor=eDP-1,2560x1440@165,0x0,1.25

# Disable a monitor
# monitor=HDMI-A-1,disable
